#!/bin/sh
# Runs the netem experiment and prints a Markdown report on stdout.
#
#   netem/run.sh > docs/benchmarks-netem.md
#
# Needs Docker. Every configuration gets fresh containers.
set -e
cd "$(dirname "$0")"
DELAY=${DELAY:-1ms}
LOSSES=${LOSSES:-"0 1 5 10"}
export JOBS=${JOBS:-10}

docker compose -f compose.yml build -q server >&2

cat <<HDR
# Benchmarks on a kernel-impaired network (netem)

Generated by \`netem/run.sh\`. Do not edit by hand; rerun instead.

Unlike [benchmarks.md](benchmarks.md), nothing here is simulated by this
repository: 1 server, 4 workers and 1 client run in separate containers on a
Docker bridge network, and each container impairs its own outgoing packets with
the Linux kernel's \`tc netem\` (delay ${DELAY} plus the loss rate shown, so both
apply independently to each direction). The scheduler, the workers and the job
are identical in every row; only \`-transport\` changes.

- Job: 40 000 000 nonces in 400 chunks of 100 000; ${JOBS} measured jobs per row
  after one warm-up job, one connection per job, every answer checked.
- Host: $(docker info --format '{{.NCPU}} CPUs, {{.OperatingSystem}}, kernel {{.KernelVersion}}, {{.Architecture}}').
- TCP is the kernel's (CUBIC, with congestion control); the reliable-UDP
  transport has a fixed window of 5 and no congestion control. Read the
  comparison as "what does this workload lose to in-order delivery and to
  loss-as-congestion", not as "this transport is better than TCP".

| Transport, loss | Job time p50 | Job time max | Job time mean | Throughput (M nonces/s) | Jobs | Failed |
|---|---|---|---|---|---|---|
HDR

for loss in $LOSSES; do
  for transport in rudp tcp; do
    export TRANSPORT=$transport NETEM="delay $DELAY loss $loss%" LABEL="$transport, $loss%"
    echo "== $LABEL" >&2
    docker compose -f compose.yml up -d --quiet-pull server worker >&2 2>/dev/null
    docker compose -f compose.yml --profile bench run --rm -T bench 2>/dev/null | grep '^|' || echo "| $LABEL | run failed | | | | | |"
    docker compose -f compose.yml --profile bench down -t 1 >&2 2>/dev/null
  done
done
